{% set base_name = "libignition-physics" %}
{% set version = "5_5.0.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version_package.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/ignitionrobotics/ign-physics/archive/ignition-physics{{ version }}.tar.gz
    sha256: e77ee0088911a5b379134466e79b7d842438378dc2b09a0fc6edf93efbe180a7
    patches:
      # - vs2017_support.patch
      - disable_fake_install.patch

build:
  number: 0
  skip: false
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libignition-cmake2
    - libignition-plugin1
    - libignition-math6
    - libignition-common4
    - libignition-utils1
    - libsdformat12
    - eigen
    - dartsim
    - libode

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/physics{{ major_version }}/ignition/physics.hh  # [not win]
    - test -f ${PREFIX}/lib/cmake/ignition-physics{{ major_version }}-dartsim/ignition-physics{{ major_version }}-dartsim-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\physics{{ major_version }}\ignition\physics.hh (exit 1)  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-physics{{ major_version }}-dartsim\\ignition-physics{{ major_version }}-dartsim-config.cmake  exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-physics
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Ignition Physics, a component of Ignition Robotics, provides an abstract physics interface designed to support simulation 
    and rapid development of robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
