{% set base_name = "libignition-physics" %}
{% set version = "3.1.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-physics/archive/ignition-physics{{ major_version }}_{{ version }}.tar.gz
    sha256: b8e5460d2808e20237b2ee0a6a6b7613b56412f5f6e2a5e153e48e8faae8ab77

build:
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }} 
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libignition-cmake2
    - libignition-plugin1
    - libignition-math6
    - libignition-common3
    - libsdformat10           # [unix]
    - eigen
    - dartsim                 # [unix]
  run:
    - libignition-math6
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/physics{{ major_version }}/ignition/physics.hh  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\physics{{ major_version }}\ignition\physics.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-physics
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Ignition Physics, a component of Ignition Robotics, provides an abstract physics interface designed to support simulation 
    and rapid development of robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
