{% set base_name = "libignition-physics" %}
{% set version = "3.0.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ base_name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-physics/archive/ignition-physics{{ major_version }}_{{ version }}.tar.gz
    sha256: 37dc31b292538dfe38c70335c80829a4721cbd86839728359f459c56fefea108

build:
  number: 0
  skip: true  # [win and vc<14 or unix]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

outputs:
  - name: {{ name }}
    version: {{ version }}
    script: bldpkg.bat
    requirements:
      build:
        - {{ compiler('cxx') }}  # [not win]
        - {{ compiler('c') }}    # [not win]
        - vs2017_win-64          # [win64]
        - cmake
        - ninja
        - pkg-config
      host:
        - libignition-cmake2
        - libignition-plugin1
        - libignition-math6
        - eigen
      run:
        - libignition-math6
    test:
      commands:
        - test -f ${PREFIX}/include/ignition/physics{{ major_version }}/ignition/physics.hh  # [not win]
        - if exist %PREFIX%\\Library\\include\\ignition\physics{{ major_version }}\ignition\physics.hh (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-physics
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Ignition Physics, a component of Ignition Robotics, provides an abstract physics interface designed to support simulation 
    and rapid development of robot applications.

extra:
  recipe-maintainers:
    - seanyen
