{% set base_name = "libignition-physics" %}
{% set version = "3.2.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-physics/archive/ignition-physics{{ major_version }}_{{ version }}.tar.gz
    sha256: c3816723fbb409275dc915544383ae02fc737b72e056c338632df8e467c1a6c7
    patches:
      - vs2017_support.patch
      - 249.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }} 
    - {{ compiler('c') }}
    # - clang  # [win]
    - cmake
    - ninja
    - pkg-config
  host:
    - libignition-cmake2
    - libignition-plugin1
    - libignition-math6
    - libignition-common3
    - libsdformat10
    - eigen
    - dartsim
    - libode

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/physics{{ major_version }}/ignition/physics.hh  # [not win]
    - test -f ${PREFIX}/lib/cmake/ignition-physics{{ major_version }}-dartsim/ignition-physics{{ major_version }}-dartsim-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\physics{{ major_version }}\ignition\physics.hh (exit 1)  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-physics{{ major_version }}-dartsim\\ignition-physics{{ major_version }}-dartsim-config.cmake  exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-physics
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Ignition Physics, a component of Ignition Robotics, provides an abstract physics interface designed to support simulation 
    and rapid development of robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
