{% set base_name = "libignition-physics" %}
{% set version = "5_5.2.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version_package.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/ignitionrobotics/ign-physics/archive/ignition-physics{{ version }}.tar.gz
    sha256: 75acb91a17c2a4988d50848355a771cfa49235ff2eb9500951c10eacc945b4d0
    patches:
      - 437.patch
      - vs2017_support.patch
      - disable_fake_install.patch
      - disable_integration_tests.patch  # [win]

build:
  number: 7
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libignition-cmake2
    - libignition-plugin1
    - libignition-math6
    - libignition-common4
    - libignition-utils1
    - libsdformat12
    - eigen
    - libccd-double
    - assimp
    # Required by dartsim 6.12.*
    - libboost-devel
    - dartsim 6.12.*
    - libode

  run:

test:
  commands:
    - test -f ${PREFIX}/include/ignition/physics{{ major_version }}/ignition/physics.hh  # [not win]
    - test -f ${PREFIX}/lib/cmake/ignition-physics{{ major_version }}-dartsim/ignition-physics{{ major_version }}-dartsim-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\physics{{ major_version }}\ignition\physics.hh (exit 1)  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-physics{{ major_version }}-dartsim\\ignition-physics{{ major_version }}-dartsim-config.cmake  exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-physics
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Ignition Physics, a component of Ignition Robotics, provides an abstract physics interface designed to support simulation 
    and rapid development of robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
